### ISSUE TITLE
Gamepad Controls

### ISSUE THREAD

**Issue by Gytaco** [theRealUnd3rdog/Godot_Noshot_Controller#10]
Are you accepting Pull Requests?

I have added Gamepad controls and Joystick to the camera aswell, and I can submit a PR.

Thanks for putting together this demo its given me a lot of ideas.

**Comment by theRealUnd3rdog** [comment]
Yeap I accept pull requests. Thanks for adding gamepad controls!

**Comment by Gytaco** [comment]
Noted with Thanks
