### ISSUE TITLE
Missing elements?

### ISSUE THREAD

**Issue by klasik16** [theRealUnd3rdog/Godot_Noshot_Controller#2]
there is errors just after loading the project:

Godot Engine v4.2.1.stable.mono.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
  modules/gltf/register_types.cpp:63 - Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
--- Debug adapter server started ---
--- GDScript language server started on port 6005 ---
  Cannot load shader: res://VolumetricSky/clouds.gdshader
  Failed loading resource: res://VolumetricSky/clouds.gdshader. Make sure resources have been imported by opening the project in the editor at least once.
  scene/resources/resource_format_text.cpp:448 - res://Materials/ProceduralSky.tres:4 - ext_resource, invalid UID: uid://gbyk8fbc1vil - using text path instead: res://VolumetricSky/perlworlnoise.tga
  Resource file not found: res://VolumetricSky/perlworlnoise.tga (expected type: CompressedTexture3D)
  scene/resources/resource_format_text.cpp:448 - res://Materials/ProceduralSky.tres:5 - ext_resource, invalid UID: uid://bgtbdcohwhp6d - using text path instead: res://VolumetricSky/weather.bmp
  Resource file not found: res://VolumetricSky/weather.bmp (expected type: Texture2D)
  scene/resources/resource_format_text.cpp:448 - res://Materials/ProceduralSky.tres:6 - ext_resource, invalid UID: uid://b0q567t0o4dha - using text path instead: res://VolumetricSky/worlnoise.bmp
  Resource file not found: res://VolumetricSky/worlnoise.bmp (expected type: CompressedTexture3D)
  scene/resources/resource_format_text.cpp:709 - res://Materials/ProceduralSky.tres:9 - Parse Error: 
  Failed loading resource: res://Materials/ProceduralSky.tres. Make sure resources have been imported by opening the project in the editor at least once.

**Comment by theRealUnd3rdog** [comment]
This seems like a problem with version 1 of the repository. My apologies. It was when I was using a volumetric sky instead of the static one I'm using at the moment. This should be fixed in the most recent commit. Please use the most recent repo.
