### ISSUE TITLE
Cannot unzip project when cloned from git bacouse of to long file name

### ISSUE THREAD

**Issue by klasik16** [theRealUnd3rdog/Godot_Noshot_Controller#4]
Please rename file with long footprint.  That the reason why cannot be unpacked after cloning zip file direct from Git using website.
You can easily test that by cloning from website entire project and try unzip it.

Renaming clone and putting it directly in to c drive helps. But still files should not be named with such long naming's.

**Comment by theRealUnd3rdog** [comment]
Just renamed it to something shorter, my apologies.
